DROP TABLE IF EXISTS EMPLOYEE_TABLE;

CREATE TABLE EMPLOYEE_TABLE(
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(100)NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(30) DEFAULT NULL
);
